benchmark:
  name: benchmark_tas_rps_alt
  template_config: configs/benchmark_matrix_template.yaml
  output_root: ${oc.env:SCRATCH}/llm_negotiation/2025_10/

environment:
  simulation_class_name: TrustAndSplitRPSSimulation
  simulation_init_args:
      nb_of_rounds: 10
      quota_messages_per_agent_per_round: 1
      alternating_hands: True

model:
  model_name: Qwen/Qwen2.5-7B-Instruct

adapters:
  trained_adapter_1: path/to/tas-rps-qwen2.57b-greedy-checkpoint/agent_adapter
  trained_adapter_2: path/to/tas_rps_alt_sum_rewards/agent_adapter
  trained_adapter_3: path/to/tas_rps_alt_ad_align/agent_adapter

common_agent_kwargs: &common_agent_kwargs
    goal: "Maximize your total points over the whole game."
    num_message_chars: 500

agents:
  - name: naive
    agent_class_name: TrustAndSplitRPSAgent
    policy_id: bench_llm/trained_adapter_1
    agent_class_kwargs:
      <<: *common_agent_kwargs
  - name: coop
    agent_class_name: TrustAndSplitRPSAgent
    policy_id: bench_llm/trained_adapter_2
    agent_class_kwargs:
      <<: *common_agent_kwargs
  - name: trained
    agent_class_name: TrustAndSplitRPSAgent
    policy_id: bench_llm/trained_adapter_3
    agent_class_kwargs:
      <<: *common_agent_kwargs

options:
  include_self_play: true
  train: false
  resume: true
  dry_run: false
  csv_summary: true
  render_keyword: nego
