# To quickly check if code still runs
experiment:
    name: "human_bob_ipd_tit_for_tat_test"
    nb_epochs: 1
    nb_matches_per_iteration: 1
    seed_group_size: 1
    train: false
    wandb_enabled: false
    base_seed: 42

defaults:
    - ipd_vanilla_ad_align.yaml


markov_games:
    simulation_init_args:
        rounds_per_game: 5
    agents:
        1:
            agent_name: Bob
            policy_id: human_policy


models:
    base_llm:
        init_args:
            initial_adapter_paths:
                agent_adapter: LLMnegotiation/ipd_vanilla_ad_align_seed42/seed_42/Qwen/Qwen2.5-7B-Instruct/adapters/agent_adapter # ensure the path is on disk
            inference_backend_init_kwargs:
                enforce_eager: True
