defaults:
    - ipd_naive.yaml

experiment:
    name: "ipd_naive_gemma3_4b_seed1337"
    base_seed: 1337

models:
    base_llm:
        init_args:
            model_name: google/gemma-3-4b-it
            enable_thinking: null
            regex_max_attempts: 1
