defaults:
    - split_no_comm_naive.yaml

experiment:
    name: "split_no_comm_naive_qwen3_8b"

models:
    base_llm:
        init_args:
            model_name: Qwen/Qwen3-8B
            enable_thinking: false
            regex_max_attempts: -1
            inference_backend_sampling_params:
                max_tokens: 20
