defaults:
    - split_no_comm_naive.yaml

experiment:
    name: "split_no_comm_naive_gemma3_4b_seed42"
    base_seed: 42

models:
    base_llm:
        init_args:
            model_name: google/gemma-3-4b-it
            enable_thinking: null
            regex_max_attempts: -1
            inference_backend_sampling_params:
                max_tokens: 20
