defaults:
    - split_no_comm_vanilla_ad_align.yaml

experiment:
    name: "split_no_comm_vanilla_ad_align_no_group_baseline_seed42"
    base_seed: 42

trainers:
    agent_trainer:
        kwargs:
            no_rloo_grouping: True
