defaults:
    - tas_rps_naive.yaml

experiment:
    name: "tas_rps_naive_gemma3_4b_seed42"
    base_seed: 42

models:
    base_llm:
        init_args:
            model_name: google/gemma-3-4b-it
            enable_thinking: null
            regex_max_attempts: 1
