defaults:
    - tas_rps_naive.yaml

experiment:
    name: "tas_rps_naive_llama3_8b"

models:
    base_llm:
        init_args:
            model_name: meta-llama/Llama-3.1-8B-Instruct
            enable_thinking: null
            regex_max_attempts: 1
