defaults:
    - tas_rps_naive.yaml

experiment:
    name: "tas_rps_naive_vs_gemini"
    nb_epochs: 500
    nb_matches_per_iteration: 64
    seed_group_size: 1
    train: true
    use_buffer: false

agent_0_id: Alice
agent_1_id: Bob
agent_ids: ["Alice", "Bob"]

markov_games:
    agents:
        0:
            agent_name: Alice
            policy_id: base_llm/agent_adapter
        1:
            agent_name: Bob
            policy_id: gemini_llm

temperature: 1.0

optimizers:
    critic_optimizer: null
    agent_optimizer:
        module_pointer: ["base_llm", "agent_adapter"]
        optimizer_class_name: torch.optim.Adam
        init_args:
            lr: 3e-6
            weight_decay: 0.0

models:
    gemini_llm:
        class: LargeLanguageModelGemini
        init_args:
            llm_id: gemini_llm
            model: gemini-3.1-flash-lite-preview
            timeout_s: 6000.0
            regex_max_attempts: 3
            thinking_level: low
            include_thoughts: true
            sampling_params:
                temperature: 1.0
                top_p: 1.0

    base_llm:
        init_args:
            regex_max_attempts: 3
            initial_adapter_paths:
                agent_adapter: /home/mila/m/mohammed.muqeeth/scratch/llm_negotiation/HF_checkpoints/tas_rps_naive_vs_gpt_oss_120b_low/seed_0/Qwen/Qwen2.5-7B-Instruct/adapters/agent_adapter
            inference_backend_init_kwargs:
                enable_prefix_caching: False
                enforce_eager: False

train_on_which_data:
    agent_trainer: ["Alice"]
